Repository Mister-Moriarty/goonstation, pull requests merged in 2024-06, with the labels that each got.

#11 Message Dissemination Refactor
  _std/defines/speech_defines/channels.dm
  _std/defines/speech_defines/modules.dm
  _std/defines/speech_defines/speech.dm
  code/modules/admin/toggles.dm
  code/modules/speech/core.dm
  code/modules/speech/modules/inputs/looc.dm
  code/modules/speech/modules/inputs/outloud/_outloud.dm
  code/modules/speech/modules/inputs/outloud/ears.dm
  code/modules/speech/modules/inputs/outloud/global_hearing.dm
  code/modules/speech/modules/inputs/shared_input_format_modules/looc.dm
  code/modules/speech/modules/module_parents.dm
  code/modules/speech/modules/outputs/_output_module_parent.dm
  code/modules/speech/modules/outputs/spoken/audio_log.dm
  code/modules/speech/outermost_listener.dm
  code/modules/speech/say_channels/_say_channel_parent.dm
  code/modules/speech/say_channels/deadchat.dm
  code/modules/speech/say_channels/equipped.dm
  code/modules/speech/say_channels/looc.dm
  code/modules/speech/say_channels/outloud.dm
  code/modules/speech/say_message.dm
  code/obj/rocko.dm
  goonstation.dme
Labels: size/XL

#12 Speaker And Listener Origin Migration
  _std/defines/component_defines/component_defines_special.dm
  _std/defines/speech_defines/channels.dm
  code/modules/speech/core.dm
  code/modules/speech/message_modifiers/admin_message.dm
  code/modules/speech/modules/inputs/flock.dm
  code/modules/speech/modules/inputs/outloud/ears.dm
  code/modules/speech/modules/inputs/outloud/global_hearing.dm
  code/modules/speech/modules/inputs/spooky.dm
  code/modules/speech/modules/modifiers/listen/admin_hearing.dm
  code/modules/speech/modules/modifiers/listen/phone_formatting.dm
  code/modules/speech/modules/modifiers/listen/radio_formatting.dm
  code/modules/speech/modules/modifiers/speech/megaphone.dm
  code/modules/speech/prefixes/_say_prefix_parent.dm
  code/modules/speech/prefixes/intercom.dm
  code/modules/speech/prefixes/left_hand.dm
  code/modules/speech/prefixes/radio.dm
  code/modules/speech/prefixes/right_hand.dm
  code/modules/speech/say_channels/_say_channel_parent.dm
  code/modules/speech/say_channels/equipped.dm
  code/modules/speech/say_channels/looc.dm
  code/modules/speech/say_channels/outloud.dm
  code/modules/speech/say_message.dm
  code/modules/speech/trees/listen_module_tree.dm
  code/modules/speech/trees/speech_module_tree.dm
  code/obj/item/device/mic_amp_etc.dm
  code/obj/item/device/radios/_radio.dm
  code/obj/machinery/computer/announcement.dm
  code/obj/machinery/phone/phone.dm
Labels: size/L

#13 Skeleton heads
  _std/defines/component_defines/component_defines_atom.dm
  code/datums/mutantraces.dm
  code/modules/speech/core.dm
  code/modules/speech/prefixes/radio.dm
  code/obj/item/organ_holder.dm
  code/obj/item/organs/head.dm
  code/procs/mobprocs/typing_indicator.dm
Labels: size/L

#14 Override Say Channel Modifier Preference
  code/modules/speech/core.dm
  code/modules/speech/modules/modifiers/listen/_listen_modifier_parent.dm
  code/modules/speech/modules/modifiers/listen/admin_hearing.dm
  code/modules/speech/modules/modifiers/speech/_speech_modifier_parent.dm
  code/modules/speech/trees/listen_module_tree.dm
  code/modules/speech/trees/speech_module_tree.dm
Labels: size/M

#15 Converts The Mixing Desk To The New Speech System
  code/modules/maptext/_maptext_holder.dm
  code/modules/speech/core.dm
  code/modules/speech/say_sources/mixing_desk.dm
  code/modules/telescience/radiostation.dm
  goonstation.dme
Labels: size/L
