Repository Mister-Moriarty/goonstation, pull requests merged in 2024-07, with the labels that each got.

#16 AI fixes
  code/mob/living/intangible/ai-camera.dm
  code/mob/living/silicon/ai.dm
  code/modules/speech/core.dm
  code/modules/speech/modules/inputs/shared_input_format_modules/ears.dm
  code/modules/speech/say_message.dm
  code/modules/speech/trees/listen_module_tree.dm
Labels: size/M

#17 Input Priority & Message Buffering
  _std/__std.dme
  _std/defines/component_defines/component_defines_special.dm
  _std/defines/speech_defines/priorities.dm
  _std/defines/speech_defines/relays.dm
  code/modules/speech/core.dm
  code/modules/speech/message_modifiers/_message_modifier_parent.dm
  code/modules/speech/message_modifiers/no_say_verb.dm
  code/modules/speech/message_modifiers/quotation_marks.dm
  code/modules/speech/message_modifiers/singing.dm
  code/modules/speech/modules/inputs/_input_module_parent.dm
  code/modules/speech/modules/inputs/flock.dm
  code/modules/speech/modules/inputs/hivechat.dm
  code/modules/speech/modules/inputs/looc.dm
  code/modules/speech/modules/inputs/radio.dm
  code/modules/speech/modules/inputs/siliconchat.dm
  code/modules/speech/modules/inputs/thrallchat.dm
  code/modules/speech/modules/modifiers/listen/_listen_modifier_parent.dm
  code/modules/speech/modules/modifiers/listen/phone_formatting.dm
  code/modules/speech/modules/modifiers/listen/radio_formatting.dm
  code/modules/speech/modules/modifiers/speech/_speech_modifier_parent.dm
  code/modules/speech/modules/modifiers/speech/accents.dm
  code/modules/speech/modules/modifiers/speech/bot.dm
  code/modules/speech/modules/modifiers/speech/mob_modifiers.dm
  code/modules/speech/modules/modifiers/speech/mutantraces/_mutantrace_modifier_parent.dm
  code/modules/speech/modules/modifiers/speech/mute.dm
  code/modules/speech/modules/modifiers/speech/muzzle.dm
  code/modules/speech/modules/modifiers/speech/revenant.dm
  code/modules/speech/modules/outputs/_output_module_parent.dm
  code/modules/speech/modules/outputs/deadchat.dm
  code/modules/speech/say_message.dm
  code/modules/speech/trees/auxiliary_listen_module_tree.dm
  code/modules/speech/trees/listen_module_tree.dm
  code/modules/speech/trees/speech_module_tree.dm
Labels: size/L

#18 Modules Trees May Now Possess Multiple Bundled Modules
  _std/defines/speech_defines/speech.dm
  code/WorkInProgress/AphsStuff.dm
  code/datums/abilities/revenant.dm
  code/datums/flock/flock.dm
  code/datums/mutantraces.dm
  code/datums/traits_disused.dm
  code/mob/dead.dm
  code/mob/dead/mentor_mouse_observer.dm
  code/mob/living/carbon/human/test.dm
  code/mob/living/carbon/human/virtual.dm
  code/mob/living/critter/flock/flockdrone.dm
  code/mob/living/critter/flockcritter_parent.dm
  code/mob/living/critter/small_animal.dm
  code/mob/living/intangible/flock/flockmind.dm
  code/mob/living/intangible/flock/flocktrace.dm
  code/mob/transform_procs.dm
  code/modules/admin/toggles.dm
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/changeling/changeling_critter.dm
  code/modules/antagonists/changeling/hivemind_member.dm
  code/modules/antagonists/vampire/thrall.dm
  code/modules/antagonists/vampire/vampire.dm
  code/modules/antagonists/wraith/abilties/_wraith_ability_holder.dm
  code/modules/events/vamp_teg.dm
  code/modules/medical/genetics/bioEffects/beneficial.dm
  code/modules/medical/genetics/bioEffects/harmful.dm
  code/modules/medical/genetics/bioEffects/speech.dm
  code/modules/mentor/mentorhelp.dm
  code/modules/robotics/bot/bot_parent.dm
  code/modules/speech/core.dm
  code/modules/speech/languages/_language_parent.dm
  code/modules/speech/message_modifiers/_message_modifier_parent.dm
  code/modules/speech/modules/inputs/_input_module_parent.dm
  code/modules/speech/modules/module_parents.dm
  code/modules/speech/modules/outputs/_output_module_parent.dm
  code/modules/speech/modules/outputs/flock.dm
  code/modules/speech/prefixes/_say_prefix_parent.dm
  code/modules/speech/prefixes/deadchat.dm
  code/modules/speech/say_channels/_say_channel_parent.dm
  code/modules/speech/say_message.dm
  code/modules/speech/say_sources/_abstract_say_source_parent.dm
  code/modules/speech/say_sources/flock_system.dm
  code/modules/speech/say_sources/mixing_desk.dm
  code/modules/speech/say_sources/random_accent.dm
  code/modules/speech/speech_manager.dm
  code/modules/speech/trees/auxiliary_listen_module_tree.dm
  code/modules/speech/trees/auxiliary_speech_module_tree.dm
  code/modules/speech/trees/listen_module_tree.dm
  code/modules/speech/trees/speech_module_tree.dm
  code/modules/vending/vending.dm
  code/obj/flock/structure/flock_structure_parent.dm
  code/obj/item/clothing/gimmick.dm
  code/obj/item/clothing/masks.dm
  code/obj/item/device/megaphone.dm
  code/obj/item/device/radios/_radio.dm
  code/obj/item/device/radios/intercoms.dm
  code/obj/item/implant.dm
  code/obj/machinery/door/door_control.dm
  code/obj/zoldorf.dm
  code/procs/mobprocs/chatprocs.dm
Labels: size/XL
